/* =====================================================================
 * REFERENCE ONLY -- NOT compiled as part of the bare-metal project.
 *
 * This shows the HAL-based equivalent of ADC_ReadRaw_REG() and the Flash
 * write helper from main.c, so you can answer Analysis Question 6
 * ("Compare your register-level and HAL implementations of
 * ADC_ReadRaw(): what does HAL do for you that you had to do manually,
 * and is there any timing/performance cost to that convenience?").
 *
 * To actually build/run this, you'd start a *separate* CubeMX project
 * with HAL drivers enabled, configure ADC1 (channel 0, resolution set
 * per call) and an hflash handle via CubeMX, then use the functions
 * below. It is NOT wired into main.c to keep the primary deliverable a
 * pure register-level implementation as the handout requires.
 * =====================================================================
 */

#include "stm32f4xx_hal.h"

extern ADC_HandleTypeDef hadc1;   /* generated by CubeMX ADC1 config */

/* HAL equivalent of ADC_ReadRaw_REG(). HAL hides:
 *   - clock enabling for the ADC peripheral
 *   - GPIO analog-mode configuration (done via MX_GPIO_Init())
 *   - the SQR/SMPR channel-configuration boilerplate
 *     (HAL_ADC_ConfigChannel() wraps it in a struct)
 *   - polling for EOC (HAL_ADC_PollForConversion() does the wait loop
 *     internally, plus a timeout you don't have to hand-roll)
 *
 * Cost: HAL_ADC_ConfigChannel() re-writes the full channel config
 * struct on every call (more registers touched than our register-level
 * version, which only rewrites CR1.RES), and the extra function-call /
 * struct-marshalling layers add a small but measurable overhead per
 * conversion compared to directly toggling ADC_CR2_SWSTART.
 */
uint32_t ADC_ReadRaw_HAL(uint32_t hal_resolution /* e.g. ADC_RESOLUTION_12B */)
{
    ADC_ChannelConfTypeDef sConfig = {0};

    hadc1.Init.Resolution = hal_resolution;
    HAL_ADC_Init(&hadc1);

    sConfig.Channel      = ADC_CHANNEL_0;
    sConfig.Rank         = 1;
    sConfig.SamplingTime = ADC_SAMPLETIME_480CYCLES;
    HAL_ADC_ConfigChannel(&hadc1, &sConfig);

    HAL_ADC_Start(&hadc1);
    HAL_ADC_PollForConversion(&hadc1, HAL_MAX_DELAY);
    uint32_t raw = HAL_ADC_GetValue(&hadc1);
    HAL_ADC_Stop(&hadc1);

    return raw;
}

/* HAL equivalent of Flash_ProgramWord(). HAL hides:
 *   - the KEYR unlock sequence (HAL_FLASH_Unlock() does both writes)
 *   - PSIZE bookkeeping for the requested program type
 *   - the busy-wait polling loop (wrapped inside FLASH_WaitForLastOperation,
 *     called internally by HAL_FLASH_Program(), with error-code returns)
 *
 * Cost: essentially none for a single word -- HAL_FLASH_Program() is a
 * fairly thin wrapper here. The bigger practical difference is API
 * ergonomics (return status codes to check) vs. raw speed.
 */
void Flash_ProgramWord_HAL(uint32_t address, uint32_t data)
{
    HAL_FLASH_Unlock();
    HAL_FLASH_Program(FLASH_TYPEPROGRAM_WORD, address, data);
    HAL_FLASH_Lock();
}
